LAP-137
litografiaUCC/employees-service pull request #2
Opened 2024-04-06 11:41 UTC by Cardona-JE

Finished the LAP-137, please review

2024-04-06 11:55 UTC, Juansecod requested changes

2024-04-06 11:55 UTC, Juansecod commented on src/main/java/com/litografiaartesplanchas/employeesservice/controller/EmployeeController.java
> +    }
If thows a Exception?

2024-04-06 11:55 UTC, Juansecod commented on src/main/java/com/litografiaartesplanchas/employeesservice/service/EmployeeService.java
> +    }
Error Management?

2024-04-06 11:55 UTC, Juansecod commented on src/main/java/com/litografiaartesplanchas/employeesservice/service/EmployeeService.java
> +    }
Error Management?

2024-04-07 16:24 UTC, Cardona-JE commented
Errors resolved, please review

2024-04-07 16:36 UTC, Juansecod approved these changes

2024-04-07 16:36 UTC, merged